/* ROW_NUMBER()
Problem 1: List the top 5 highest salaries in each department. */

WITH TOP5 AS (

SELECT FIRST_NAME AS EMP_NAME , 
SALARY , 
DEPARTMENT ,

ROW_NUMBER() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS ROW_RANKS
FROM EMP
)

SELECT * FROM TOP5 WHERE ROW_RANKS <=5;
