CREATE 
TABLE famous 
 (user_id INT, follower_id INT); 

INSERT INTO famous VALUES 
(1, 2), (1, 3), (2, 4), (5, 1), (5, 3),
(11, 7), (12, 8), (13, 5), (13, 10), 
(14, 12), (14, 3),(15, 14), (15, 13);

SELECT * FROM FAMOUS ;
   
WITH X AS (
	SELECT USER_ID FROM FAMOUS
	UNION
	SELECT FOLLOWER_ID FROM FAMOUS
)
SELECT X.USER_ID , 
	COUNT(F.FOLLOWER_ID)*100 / (SELECT COUNT(DISTINCT (X.USER_ID)) FROM X) AS PERCENTAGES 
	FROM X
   LEFT JOIN
   FAMOUS  AS F
   ON F.USER_ID = X.USER_ID
   GROUP BY X.USER_ID
