--NOT INNER JOIN ALSO KNOWN AS FULL OUTER JOIN RETURN NULL VALUES FROM BOTH TABLE
SELECT * FROM EMPLOYEES1 FULL OUTER JOIN EMPLOYEES2 ON EMPLOYEES1.EMP_ID = EMPLOYEES2.ID WHERE EMPLOYEES2.ID IS NULL OR EMPLOYEES1.EMP_ID IS NULL;
